### ISSUE TITLE
error page

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-skeleton-receptar-site#4]
How to hide the error page in the menu?

**Comment by pieplu** [comment]
On `site.yaml` file, you can found that:
```yaml
menu:
  - url: error
    text: Error Page
```

Remove the item :)
